### PR TITLE
Improved presentation and variables names in ms_OOI_EK60* notebook

### PR DESCRIPTION
**Pull request by emiliom**
But note that it is currently failing. *May* have to do with the use of an echopype 0.5.0 env and the lower-version dependencies it carries?

### CODE REVIEW

**Comment by leewujung** [comment]
Is the reason for using echopype 0.5.0 env due to the location_time regression problem?

**Comment by emiliom** [comment]
Yes

**Comment by emiliom** [comment]
The bug doesn't affect this notebook, but I'm using the same conda env for
both notebooks

**Comment by leewujung** [comment]
:/ we really need to get that fixed.

**Pull request merged**
