### PR TITLE
Update notebooks to 0.6.3, index/front page, and README

### PR DESCRIPTION
**Pull request by emiliom**
Update the 3 notebooks to run with 0.6.3. Includes:
- Replace explicit code with `ep.consolidate.swap_dims_channel_frequency`, introduced after 0.6.0
- In each notebook, fix link to conda `environment.yml` file
- Small polish to text such as typos; and for the OOI notebook, removed a stray sentence that shouldn't have been there
- Replace the index (front page) notebook with a markdown file, `index.md`. That's much easier to maintain and update.

Updated the front page with information about creating the conda environment and running it in binder (I copied and tweaked the binder info from the README); and added information to the README file about building the JupytertBook locally.

Note: In the hake notebook, I removed cell 2 *after* running the notebook, so the cell numbering now skips from cell 1 to cell 3. I had added an `ep.verbose` statement in cell 2, but I later realized that it was unnecessary b/c the behavior I was specifying was already the default.

### CODE REVIEW

**Comment by leewujung** [comment]
Yes!

**Comment by emiliom** [comment]
> How about we edit the title of the OOI notebook so it specifically says "OOI"? eg: "Watching a solar eclipse using an OOI moored echosounder"

Done

**Comment by leewujung** [comment]
Ok, thanks @emiliom , I've finally reviewed this. Everything looks good and I made some minor suggested changes. I think the main README to benefit from adding some subheadings, but in the spirit to getting this updated first, feel free to merge after those changes are done. I'll do a separate PR on the subheadings.

**Comment by emiliom** [comment]
Thanks for the review. I've pushed the changes you suggested; BTW, wouldn't it be nice if GitHub + ReviewNB allowed for direct suggestions to be made for notebook markdown cells, and for direct merging?!

Feel free to submit a PR for the README file any time :stuck_out_tongue_winking_eye: 

Merging. Woo-hoo!

**Pull request merged**
