### PR TITLE
Setup jupyterbook

### PR DESCRIPTION
**Pull request by lsetiawan**
This PR adds Jupyter Book configuration, but not automated build for when we choose to move forward with it. I figured that if the config is outside the notebooks folder, we can still keep the current notebooks structure without adding additional files that can confuse users.

## Built site demo

Screenshot from 2021-11-03 11-14-20

## To try it out locally

1. Install jupyter-book: `conda install -c conda-forge --yes jupyter-book`
2. From repo root build the book: `jupyter-book build --config $PWD/jupyterbook/config.yml --toc $PWD/jupyterbook/toc.yml notebooks`
3. Open the `index.html` in a browser. That file is located at `notebooks > _build > html`.

### CODE REVIEW

**Comment by lsetiawan** [comment]
Just a comment that the binder links within the jupyter book works like a charm without additional configurations! 😄

**Comment by emiliom** [comment]
Thank you @lsetiawan !! Brilliant! I'll try to review this today.

**Comment by lsetiawan** [comment]
Sounds good. I put the instruction to build it above.

**Comment by emiliom** [comment]
This is awesome, @lsetiawan . I love that it's minimalist Jupyter Book "layer" on top of everything we already have. It reuses the index notebook, and so on. Plus I totally agree that it's best keeping the jb files outside the `notebooks` folder.

It'd be great if `images/logo.png` was not added to the `notebooks` folder either, but maybe that's not doable given `path_to_book: notebooks` in `config.yml`

I've tested it locally, and it works and looks great. Thanks!

@leewujung do you want to give it a look before we merge? To maybe spare you some work, here's a screenshot of the front page. As you can see, that's `index.ipynb` in the main body:
image

**Comment by leewujung** [comment]
This looks great! How about adding one more [badge](https://jupyterbook.org/web/badge.html) to the repo?  😃

**Comment by lsetiawan** [comment]
> It'd be great if images/logo.png was not added to the notebooks folder either, but maybe that's not doable

Yea I tried reusing the logo from the echopype repo but it doesn't seem to work with jupyter-book. It needs a regular file path to the image from the notebooks folder not URL. Oh well. Maybe we can reuse that folder for other figures that gets pulled into the notebooks in the future 🙂

**Comment by lsetiawan** [comment]
@emiliom One question for you. Is there a reason that the index page is using jupyter notebook rather than a plain markdown file?

**Comment by emiliom** [comment]
> Yea I tried reusing the logo from the echopype repo but it doesn't seem to work with jupyter-book. It needs a regular file path to the image from the notebooks folder not URL. Oh well. 

In principle, the toc.yml and config.yml files could also be moved, say, to the repo root, then an image folder outside the notebooks folder would work. But I kind of like what you've done, stuffing them in their own folder so that most users won't see them.

> Maybe we can reuse that folder for other figures that gets pulled into the notebooks in the future

That's a good suggestion. If life gives you lemons ...

**Comment by emiliom** [comment]
> @emiliom One question for you. Is there a reason that the index page is using jupyter notebook rather than a plain markdown file?

Good question. I borrowed the scheme from something we've done in OceanHackWeek and other contexts where the expectation is that users will be on Jupyter (lab/classic) and will navigate multiple notebooks. A notebook-based index is very convenient in that context. Likewise, for providing an entry point from nbviewer.org, and binder. With a JupyterBook, the value of it being a notebook rather than markdown is decreased. But it may still be convenient and helpful for users running the notebooks locally on JupyterLab.

**Comment by lsetiawan** [comment]
> A notebook-based index is very convenient in that context.

Gotcha. It makes sense. Okay. No problem. In that case, maybe adding a link back to this index would be useful in each of the example notebook. 😄

**Comment by lsetiawan** [comment]
> That's a good suggestion. If life gives you lemons ...

make a lemonade! 🍋

**Comment by emiliom** [comment]
So, where are we with this PR? Should it be merged now?

Other small suggestions have come up, but I don't think any of them should hold up the PR. 

@lsetiawan have you tested the deployment of the jupyter book? Will it be at https://osoceanacoustics.github.io/echopype-examples?

**Comment by lsetiawan** [comment]
> have you tested the deployment of the jupyter book?

Nope. Not yet. Can't until it's in main haha

**Comment by lsetiawan** [comment]
Go ahead and merge when you're ready @emiliom

**Comment by leewujung** [comment]
Should we just merge this?

**Comment by lsetiawan** [comment]
Self-merging.

**Pull request merged**
